name: Run Python Script

on:
  push:
    branches:
      - main  # Run this action when code is pushed to the main branch
  workflow_dispatch:  # Allow manual trigger of the workflow from GitHub Actions

jobs:
  run_python:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up the Python environment
        with:
          python-version: '3.x'  # Use Python 3.x (you can specify a version like '3.8')

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements file, skipping..."

      - name: Run Python script
        run: python indianexpress.py  # Replace 'example.py' with your script name
