name: Run Python Script

on:
  schedule:
    # Runs at 12 AM CST every day
    - cron: '0 7 * * *'  # 12 AM CST is 6 AM UTC

jobs:
  run_python:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v5  # Set up the Python environment
        with:
          python-version: '3.x'  # Use Python 3.x (you can specify a version like '3.8')

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements file, skipping..."

      - name: Set up credentials
        run: |
          echo "$gsheet" > credentials.json
        env:
          gsheet: ${{ secrets.gsheet }}

      - name: Run Python script
        run: python indianexpress.py  # Replace 'example.py' with your script name
